# Generated by Django 4.1.3 on 2023-03-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256)),
                ('address_a', models.CharField(max_length=256)),
                ('address_b', models.CharField(max_length=256)),
                ('weigth', models.FloatField(blank=True, null=True)),
                ('gabarits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_customer.gabarits')),
            ],
        ),
    ]
