# Generated by Django 4.1.3 on 2023-03-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0006_alter_orders_status_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabarits',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gabarits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_customer.gabarits', to_field='name'),
        ),
    ]
